### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by VSSheep** [blastentwice/CK3-Family-Tree-Exporter-To-Gramps-Fast-JSON-Version#1]
Hello

The CSV creation on step 2 is throwing an error:
`Traceback (most recent call last):
File "ck3json.py", line 2472, in <module>
File "ck3json.py", line 626, in getpersonOG
IndexError: list index out of range`

This is after entering all options including the character ID.

**Comment by blastentwice** [comment]
A problem with custom religions. Will be addressed after the Royal Court DLC is released.
